### ISSUE TITLE
CMake Error at E:/GamesSources/Rayne/Source/CMakeLists.txt:358 (message):   Setup API library not found

### ISSUE THREAD

**Issue by YupCore** [uberpixel/Rayne#1]
I have this error when building project from pyton script(CreateBuildProject.py). I've googled it and this library should be in windows sdk but what version? I've done everything from readme

Here are logs
[CMakeError.log](https://github.com/uberpixel/Rayne/files/8225713/CMakeError.log)
[CMakeOutput.log](https://github.com/uberpixel/Rayne/files/8225714/CMakeOutput.log)

**Comment by Slin** [comment]
Hey, you'll have to point cmake at the file manually at the moment. The actual version doesn't really matter, any windows 10 SDK should work.

The path should be something like: C:/Program Files (x86)\Windows Kits/10/Lib/10.0.17763.0/um/x64/SetupAPI.lib

**Comment by YupCore** [comment]
Strangely that directory contains SetupAPI.lib but why am I getting this error?

**Comment by Slin** [comment]
Because make isn't finding it. You can open the CmakeCache.txt (or something like that) in your build directory and search for SETUPAPI in it, the value will be NOT-FOUND. You can change it to point at your file, save and run cmake in your build directory (don't use the python script again as it will recreate the directory, deleting the file you just changed).
I need to fix that :(
